### ISSUE TITLE
JUnit-XML Output

### ISSUE THREAD

**Issue by bailey84j** [thegeeklab/ansible-later#577] opened 2023-04-03 15:46 UTC
The JSON Logging does not seem to working, it there any way to allow for artefacts / test results to be created for example as junit results

**Comment by xoxys** [comment] 2023-04-03 19:01
The JSON logger is working as intended with the latest release if it was enabled in the configuration and can be used for custom parsers:

```JSON
{"asctime": "2023-04-03 20:58:26,560", "levelname": "WARNING", "message": "[ANSIBLE9998] Best practice 'Standards version should be pinned' not met: meta/main.yml: Standards version not set. Using latest standards version 0.2", "later_tag": "review", "later_standard": "Standards version should be pinned", "later_file": "meta/main.yml", "later_passed": false, "later_sid": "ANSIBLE9998", "later_lineno": null, "later_message": "Standards version not set. Using latest standards version 0.2"}
{"asctime": "2023-04-03 20:58:26,561", "levelname": "ERROR", "message": "[ANSIBLE0002] Standard 'Roles must contain suitable meta/main.yml' not met: meta/main.yml: file should contain `galaxy_info` key", "later_tag": "review", "later_standard": "Roles must contain suitable meta/main.yml", "later_file": "meta/main.yml", "later_passed": false, "later_sid": "ANSIBLE0002", "later_lineno": null, "later_message": "file should contain `galaxy_info` key"}
```

As I don't have any plan to add other loggers, I'm going to close the issue. If someone still wants to contribute another logging format, I will consider it again.

**Closed by xoxys** 2023-04-03 19:01 UTC

**Comment by bailey84j** [comment] 2023-04-04 07:49
Hi, I am have this config file and have tried all log levels

```
---
# Global logging configuration
# If you would like to force colored output (e.g. non-tty)
# set environment variable `PY_COLORS=1`
logging:
  # You can enable JSON logging if a parsable output is required
  json: True

  # Possible options debug | info | warning | error | critical
  level: info
```

and run these commands and variants of it but can't seem to get the json out

```
ansible-later -c .ansible-later > test.json 2>&1
ansible-later -c .ansible-later > test.json 
```

I want to get the json which I can upload as an artifact

**Comment by bailey84j** [comment] 2023-04-06 12:23
Hi this is a sample of the output I get rather than a json

```
WARNING: [ANSIBLE9998] Best practice 'Standards version should be pinned' not met:
... template.yml: Standards version not set. Using latest standards version 0.2

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... template.yml:5: missing document end "..."

WARNING: [ANSIBLE9998] Best practice 'Standards version should be pinned' not met:
... tests/oauth/ldap/oauth/ldapsyncconfig.enc.doc.yaml: Standards version not set. Using latest standards version 0.2
```

**Comment by xoxys** [comment] 2023-04-06 12:26
Still can't reproduce ... What's the output of `ansible-later --version`?
